#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test "$(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0')"
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

echo "--- Beginning DFI pre-commit checks ---"
echo
# For each file which has been changed, look for haproxy.cfg (the only file
# of interest):
for file in $(git diff-index --diff-filter=AMDC --name-only --cached HEAD); do
    case ${file} in
	haproxy.cfg)
	    echo ">> Creating a backup copy of haproxy.cfg, according to procedure"
	    # Put the modified state in the stash amd create
            # a backup: 
	    ds=`date "+%Y%m%d_%H%M%S"`
	    bak=haproxy.cfg.${ds}
	    echo ">> Creating backup file ${bak}"
	    git show HEAD:haproxy.cfg > ${bak}
	    echo -en ">> Checking that the HAProxy configuration file is valid: "
	    ${HAPROXY_BIN:-/usr/sbin/haproxy} -c -f haproxy.cfg >/dev/null 2>&1
	    if [[ $? -ne 0 ]]; then
		echo "*** FAILED: haproxy.cfg is invalid. Please fix, add the changes and try to commit again. ***"
		exit 1
	    else
		echo "[OK]"
	    fi
	    ;;
	*)
	    echo "OK: Skipping pre-commit checks on ${file}."
    esac
done
echo
# Final step (whitespace checks etc.):
exec git diff-index --check --cached $against --
